# Generated by Django 6.0.4 on 2026-05-22 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('idade', models.IntegerField()),
                ('curso', models.CharField(max_length=120)),
                ('matricula', models.CharField(max_length=20, unique=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
    ]
